name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar ambiente Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Executar testes automatizados
        run: node teste.js
